server:
  port: 18081
spring:
  application:
    name: dubbo-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gcdic?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root12345
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.zjy.dubbo.api  #dubbo中包扫描

mybatis-plus:
  global-config:
    db-config:
      #table-prefix: tb_   # 表名前缀
      id-type: auto   # id策略为自增长
logging:
  level:
    com.zjy.dubbo: debug
